# Generated by Django 5.0.8 on 2024-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
